### ISSUE TITLE
totalspaces does not install to /Applications/

### ISSUE THREAD

**Issue by wickles** [sscotth/homebrew-sip#3]
I'm not sure what happened but totalspaces does not install to `/Applications/` anymore. It just installs to the `Caskroom` folder and asks the user to run from there.

**Comment by sscotth** [comment]
https://github.com/Homebrew/homebrew-cask/pull/7197

I think this was intentional. The `TotalSpaces.app` isn't a normal app, and simply an installer. Which means you only need to run the app once and you will never need it again. Thus, I think the intention is to leave it out of the Applications folder.

```
==> Installing Cask totalspaces
To complete the installation of Cask totalspaces, you must also
run the installer at:
  '/usr/local/Caskroom/totalspaces/2.7.4/TotalSpaces2.app'
🍺  totalspaces was successfully installed!
```

Thanks for reporting!
